### ISSUE TITLE
Blynk.sync does not work

### ISSUE THREAD

**Issue by Anrikigai** [Barbayar/EasyBlynk8266#5]
I've used this library with a big pleasure for a while. But recently I've decided to restore my data from the server to ESP on restart.
I've tried to call Blynk.syncVirtual(V1) or even Blynk.syncAll() but they do not trigger BLYNK_WRITE(V1).
When I remove this library and keep only <Blynk.h>,<ESP8266WiFi.h>,<BlynkSimpleEsp8266.h> it starts working as Blynk documentation describes.

Could you please fix it or suggest any workaround?
I'd like to keep using this library in my projects as it is very convenient.

**Comment by Barbayar** [comment]
Hi @Anrikigai, sorry for a delayed response. I wrote this library during my vacation as a hobby project. Now, I'm back to work, and I forgot everything I learned during my Arduino projects.
So, I cannot maintain this library anymore.

I'm sorry.

**Comment by felmue** [comment]
@Anrikigai have you tried to only include <EasyBlynk8266.h> but _not_ <BlynkSimpleEsp8266.h> and then replace Blynk.syncVirtual(V1) with EasyBlynk8266.syncVirtual(V1)?

Background: if you include <EasyBlynk8266.h> _and_ <BlynkSimpleEsp8266.h> you end up with two blynk objects: Blynk and EasyBlynk8266, but only EasyBlynk8266 is actually active and connected. (at least that is what happened to me)

**Comment by Anrikigai** [comment]
> replace Blynk.syncVirtual(V1) with EasyBlynk8266.syncVirtual(V1)
Probably that was my mistake.
I'll try. Thank you!
